spring:
    profiles:
        # 默认激活 dev 环境
        active: dev
jwt:
    # 签发人
    issuer: zhaorenyi
    # 秘钥
    secret: jElxcSUj38+Bnh73T68lNs0DfBSit6U3whQlcGO2XwnI+Bo3g4xsiCIPg8PV/L0fQMis08iupNwhe2PzYLB9Xg==
    # token 过期时间（单位：分钟） 24*60
    tokenExpireTime: 10
    # token 请求头中的 key 值
    tokenHeaderKey: Authorization
    # token 请求头中的 value 值前缀
    tokenPrefix: Bearer
